import { createContext, useContext, useState } from 'react'

const translations = {
  en: {
    appName: 'ResellTracker',
    dashboard: 'Dashboard',
    inventory: 'Inventory',
    addItem: '+ Add Item',
    logout: 'Sign out',
    loading: 'Loading...',
    listedItems: 'Active Listings',
    soldItems: 'Items Sold',
    totalRevenue: 'Total Revenue',
    totalProfit: 'Total Profit',
    vatSummary: '🧾 VAT Summary (25%)',
    revenueInclVat: 'Revenue incl. VAT',
    vatToPay: 'VAT to pay (25%)',
    revenueExclVat: 'Revenue excl. VAT',
    profitExclVat: 'Profit excl. VAT',
    vatNote: '⚠️ VAT only applies if you are registered for VAT. If you are under the threshold (80,000 kr/year), you may not need to charge VAT. Consult Skatteverket or an accountant.',
    whatCustomersPaid: 'What customers paid',
    owedToTax: 'Owed to Skatteverket',
    actualRevenue: 'Your actual revenue',
    afterCosts: 'After costs and VAT',
    thisWeek: 'This week',
    thisMonth: 'This month',
    last3Months: 'Last 3 months',
    thisYear: 'This year',
    allTime: 'All time',
    photo: 'Photo',
    item: 'Item',
    brand: 'Brand',
    size: 'Size',
    bought: 'Bought',
    listed: 'Listed',
    platform: 'Platform',
    status: 'Status',
    profit: 'Profit',
    actions: 'Actions',
    markSold: 'Mark sold',
    edit: 'Edit',
    delete: 'Delete',
    exportCSV: '⬇ Export CSV',
    noPhoto: 'No photo',
    noItems: 'No items yet. Add your first item!',
    active: 'Active',
    sold: 'Sold',
    addNewItem: 'Add New Item',
    itemName: 'Item name *',
    itemNamePlaceholder: "e.g. Levi's 501 W30 L32",
    brandPlaceholder: "e.g. Levi's",
    sizePlaceholder: 'e.g. W30 L32',
    purchasePrice: 'Purchase price (kr)',
    listingPrice: 'Listing price (kr)',
    datePurchased: 'Date purchased (optional)',
    notes: 'Notes',
    notesPlaceholder: 'Any extra details...',
    photoOptional: 'Photo (optional)',
    saveItem: 'Save Item',
    saving: 'Saving...',
    itemNameRequired: 'Item name is required',
    salePricePrompt: 'Sale price (kr)?',
    deleteConfirm: 'Are you sure you want to delete this item?',
    editName: 'Name:',
    editBrand: 'Brand:',
    editSize: 'Size:',
    editPurchase: 'Purchase price:',
    editListing: 'Listing price:',
    editNotes: 'Notes:',
    signIn: 'Sign in to your account',
    createAccount: 'Create your account',
    email: 'Email',
    emailPlaceholder: 'you@example.com',
    password: 'Password',
    signInBtn: 'Sign In',
    createAccountBtn: 'Create Account',
    alreadyHaveAccount: 'Already have an account? Sign in',
    noAccount: "Don't have an account? Sign up",
    confirmEmail: 'Check your email to confirm your account!',
    chooseLanguage: 'Choose your language',
    continue: 'Continue',
    settings: 'Settings',
    vatRate: 'VAT rate (%)',
    vatRateDesc: 'Set your VAT rate. Default in Sweden is 25%.',
    save: 'Save',
    saved: 'Saved!',
  },
  sv: {
    appName: 'ResellTracker',
    dashboard: 'Översikt',
    inventory: 'Lager',
    addItem: '+ Lägg till',
    logout: 'Logga ut',
    loading: 'Laddar...',
    listedItems: 'Aktiva annonser',
    soldItems: 'Sålda varor',
    totalRevenue: 'Total omsättning',
    totalProfit: 'Total vinst',
    vatSummary: '🧾 Momssammanfattning (25%)',
    revenueInclVat: 'Omsättning inkl. moms',
    vatToPay: 'Moms att betala (25%)',
    revenueExclVat: 'Omsättning exkl. moms',
    profitExclVat: 'Vinst exkl. moms',
    vatNote: '⚠️ Moms gäller bara om du är momsregistrerad. Om du är under gränsen (80 000 kr/år) behöver du troligtvis inte ta ut moms. Rådfråga Skatteverket eller en revisor.',
    whatCustomersPaid: 'Vad kunderna betalade',
    owedToTax: 'Till Skatteverket',
    actualRevenue: 'Din faktiska omsättning',
    afterCosts: 'Efter kostnader och moms',
    thisWeek: 'Denna vecka',
    thisMonth: 'Denna månad',
    last3Months: 'Senaste 3 månaderna',
    thisYear: 'Detta år',
    allTime: 'Alltid',
    photo: 'Foto',
    item: 'Vara',
    brand: 'Märke',
    size: 'Storlek',
    bought: 'Inköpt',
    listed: 'Utrop',
    platform: 'Plattform',
    status: 'Status',
    profit: 'Vinst',
    actions: 'Åtgärder',
    markSold: 'Markera såld',
    edit: 'Redigera',
    delete: 'Ta bort',
    exportCSV: '⬇ Exportera CSV',
    noPhoto: 'Ingen bild',
    noItems: 'Inga varor ännu. Lägg till din första vara!',
    active: 'Aktiv',
    sold: 'Såld',
    addNewItem: 'Lägg till vara',
    itemName: 'Varunamn *',
    itemNamePlaceholder: "t.ex. Levi's 501 W30 L32",
    brandPlaceholder: "t.ex. Levi's",
    sizePlaceholder: 't.ex. W30 L32',
    purchasePrice: 'Inköpspris (kr)',
    listingPrice: 'Utropspris (kr)',
    datePurchased: 'Inköpsdatum (valfritt)',
    notes: 'Anteckningar',
    notesPlaceholder: 'Övrig information...',
    photoOptional: 'Foto (valfritt)',
    saveItem: 'Spara vara',
    saving: 'Sparar...',
    itemNameRequired: 'Varunamn krävs',
    salePricePrompt: 'Försäljningspris (kr)?',
    deleteConfirm: 'Är du säker på att du vill ta bort denna vara?',
    editName: 'Namn:',
    editBrand: 'Märke:',
    editSize: 'Storlek:',
    editPurchase: 'Inköpspris:',
    editListing: 'Utropspris:',
    editNotes: 'Anteckningar:',
    signIn: 'Logga in på ditt konto',
    createAccount: 'Skapa ditt konto',
    email: 'E-post',
    emailPlaceholder: 'du@exempel.se',
    password: 'Lösenord',
    signInBtn: 'Logga in',
    createAccountBtn: 'Skapa konto',
    alreadyHaveAccount: 'Har du redan ett konto? Logga in',
    noAccount: 'Har du inget konto? Registrera dig',
    confirmEmail: 'Kontrollera din e-post för att bekräfta ditt konto!',
    chooseLanguage: 'Välj språk',
    continue: 'Fortsätt',
    settings: 'Inställningar',
    vatRate: 'Momssats (%)',
    vatRateDesc: 'Ange din momssats. Standard i Sverige är 25%.',
    save: 'Spara',
    saved: 'Sparat!',
  }
}

const LanguageContext = createContext()
export const useLanguage = () => useContext(LanguageContext)

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(null)
  const t = lang ? translations[lang] : translations['en']
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
